import { useAppStore } from "@/store/app";
import localFont from "next/font/local";
import { useWalletStore } from "@/store/wallet";
import { useAddress } from "@meshsdk/react";
import Head from "next/head";
import { useAccount } from "wagmi";
import { Comfortaa } from "next/font/google";
import Background from "@/components/BackGround";

const comfortaa_font = Comfortaa({
  subsets: ["latin"],
  variable: "--font-comfortaa",
  weight: ["400", "500", "600", "700"],
});

const thunder_regular_font = localFont({
  src: "../../public/fonts/MonumentExtended-Regular.otf",
  variable: "--font-monument-regular",
});
const thunder_bold_font = localFont({
  src: "../../public/fonts/MonumentExtended-Ultrabold.otf",
  variable: "--font-monument-bold",
});

export default function Home() {
  const { setModal } = useAppStore();
  const { account } = useWalletStore()
  const { address } = useAccount()
  const addr = useAddress()
  return (
    <>
      <Head>
        <title>NuIPX</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background />
      <button onClick={() => console.log(address)}>aaaaaa</button>
      <div className={`${comfortaa_font.className} relative min-h-screen text-white ${thunder_regular_font.variable} ${thunder_bold_font.variable}`}>
        {/* <h1 className={thunder_regular_font.className + " my-6 text-center text-2xl uppercase"}>NUIPx</h1> */}
        <div className="container mx-auto px-4 py-8">
          <main className="flex flex-col gap-3">
            {/* NUIPX Log */}
            <div className="flex gap-3">
              <div className="bg-[#0F0F0F] rounded-3xl flex-1 rounded-lg p-4">
                <div className="flex justify-between">
                  <h2 style={{
                    color: "rgba(255, 255, 255, 0.67)"
                  }} className="font-semibold mb-4">NUIPX Log</h2>
                  <div className="flex items-center justify-between mb-2 font-semibold">
                    <select className="bg-[#121212] text-white rounded px-2 py-1">
                      <option>Dropdown</option>
                    </select>
                  </div>
                </div>
                <div className='flex flex-col gap-5 mt-7'>
                  <div className='flex justify-between items-center'>
                    <div>
                      <div className="text-base">nuclear-Desci <GreyColorSpan txt="royalty paid" /> <span className="text-green-400">10RLUSD</span></div>
                      <div className="flex items-center justify-between text-base mb-2">
                        <div><GreyColorSpan txt="By Research Agent:" /> Child IPA</div>
                      </div>
                    </div>
                    <View />
                  </div>
                  <div className='flex justify-between items-center'>
                    <div>
                      <div className="text-base">nuclear-Desci royalty paid <span className="text-green-400">10RLUSD</span></div>
                      <div className="flex items-center justify-between text-base mb-2">
                        <div><GreyColorSpan txt="By Research Agent:" /> Child IPA</div>

                      </div>
                    </div>
                    <View />
                  </div>
                  <div className='flex justify-between items-center'>
                    <div>
                      <div className="text-base">nuclear-Desci royalty paid <span className="text-green-400">10RLUSD</span></div>
                      <div className="flex items-center justify-between text-base">
                        <div><GreyColorSpan txt="By Research Agent:" /> Child IPA</div>

                      </div>
                    </div>
                    <View />
                  </div>
                </div>
              </div>
              <div className={'flex flex-1 h-full flex-col gap-3 ' + comfortaa_font.className}>
                {/* Your IP Assets */}
                <div className="bg-[#0F0F0F] rounded-2xl py-4">
                  <h2 style={{
                    color: "rgba(255, 255, 255, 0.67)"
                  }} className="font-semibold mb-4 px-4 uppercase">Your IP Assets</h2>
                  <div className="bg-[#141623] px-4 py-3 flex justify-between mb-6 font-semibold">
                    <div className="text-gray-400">IPA</div>
                    <div className="text-gray-400">Earnings</div>
                  </div>
                  <div className="px-4 flex justify-between mb-6">
                    <div>Bahubali-RFC</div>
                    <div><span className="text-green-400">100 RLUSD</span></div>
                  </div>
                  <div className="px-4 flex justify-between mb-6">
                    <div>Katsushika-Hokusai</div>
                    <div><span className="text-green-400">100 RLUSD</span></div>
                  </div>
                  <div className="px-4 flex justify-between mb-10">
                    <div>Nuclear-BSR</div>
                    <div><span className="text-green-400">100 RLUSD</span></div>
                  </div>
                </div>
              </div>
            </div>
            <div className={'flex h-[155px] flex-col gap-3 bg-[#0F0F0F] rounded-2xl p-6 ' + comfortaa_font.className}>
              <h2 style={{
                color: "rgba(255, 255, 255, 0.67)"
              }} className="font-semibold mb-4 uppercase">Mint IP Asset</h2>
              <div className="flex gap-3">
                <button onClick={() => setModal("UPLOAD_DESCI")} className="flex justify-between flex-1 rounded-2xl bg-[#121212] uppercase p-5 font-black">desci <GitMergeSvg /></button>
                <button onClick={() => setModal("UPLOAD_MEDIA")} className="flex justify-between flex-1 rounded-2xl bg-[#121212] uppercase p-5 font-black">Media <MediaSvg /></button>
              </div>
            </div>
            <div className="flex gap-3">
              <div className={'flex-1 flex gap-3 bg-[#0F0F0F] rounded-2xl items-center justify-between p-6 ' + comfortaa_font.className}>
                <h2 style={{
                  color: "rgba(255, 255, 255, 0.67)"
                }} className="font-semibold uppercase">Total Earning</h2>
                <p className="font-black">1100 RLUSD</p>
              </div>
              <div className={'flex-1 flex gap-3 bg-[#0F0F0F] rounded-2xl items-center justify-between p-6 ' + comfortaa_font.className}>
                <h2 style={{
                  color: "rgba(255, 255, 255, 0.67)"
                }} className="font-semibold uppercase">Average Daily Earning</h2>
                <p className="font-black">1100 RLUSD</p>
              </div>
            </div>
            <div className={'flex flex-col gap-3 bg-[#0F0F0F] rounded-2xl p-6 ' + comfortaa_font.className}>
              <h2 style={{
                color: "rgba(255, 255, 255, 0.67)"
              }} className="font-semibold mb-4 uppercase">Current IPA licensing</h2>
              <div className="flex gap-3">
                <div className="flex flex-col justify-between flex-1 rounded-2xl bg-[#121212] uppercase p-5 gap-24 font-black"><span>Bahubali-RFC</span> <span>{"{Art-Direction-Agent}"} </span></div>
                <div className="flex flex-col justify-between flex-1 rounded-2xl bg-[#121212] uppercase p-5 gap-24 font-black"><span>Katsushika-Hokusai </span><span>{"{Japanese-Art-Agent}"}</span></div>
                <div className="flex flex-col justify-between flex-1 rounded-2xl bg-[#121212] uppercase p-5 gap-24 font-black"><span>Nuclear-BSR </span><span>{"{DeSci-Research-Agent}"}</span></div>
              </div>
            </div>
          </main>
        </div >
      </div >
    </>
  );
}

function View() {
  return <button className="text-white py-2 px-3 rounded-lg text-sm bg-[#242424]">
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 22 22" fill="none">
      <path d="M21.2532 10.7216C21.2231 10.6537 20.4952 9.03891 18.877 7.4207C16.7209 5.26453 13.9975 4.125 11 4.125C8.00249 4.125 5.27913 5.26453 3.12296 7.4207C1.50476 9.03891 0.773429 10.6562 0.746789 10.7216C0.707698 10.8095 0.6875 10.9046 0.6875 11.0009C0.6875 11.0971 0.707698 11.1922 0.746789 11.2802C0.776867 11.348 1.50476 12.962 3.12296 14.5802C5.27913 16.7355 8.00249 17.875 11 17.875C13.9975 17.875 16.7209 16.7355 18.877 14.5802C20.4952 12.962 21.2231 11.348 21.2532 11.2802C21.2923 11.1922 21.3125 11.0971 21.3125 11.0009C21.3125 10.9046 21.2923 10.8095 21.2532 10.7216ZM11 14.4375C10.3201 14.4375 9.65551 14.2359 9.09022 13.8582C8.52493 13.4805 8.08433 12.9436 7.82416 12.3155C7.56398 11.6874 7.49591 10.9962 7.62854 10.3294C7.76118 9.66257 8.08857 9.05006 8.56931 8.56932C9.05006 8.08858 9.66256 7.76119 10.3294 7.62855C10.9962 7.49591 11.6873 7.56399 12.3155 7.82416C12.9436 8.08434 13.4805 8.52493 13.8582 9.09023C14.2359 9.65552 14.4375 10.3201 14.4375 11C14.4375 11.9117 14.0753 12.786 13.4307 13.4307C12.786 14.0753 11.9117 14.4375 11 14.4375Z" fill="#AFAFAF" />
    </svg>
  </button>
}

function GreyColorSpan({ txt }: { txt: string }) {
  return <span style={{ color: "rgba(255, 255, 255, 0.67)" }}>{txt}</span>
}

function GitMergeSvg() {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
    <path d="M19.4995 10.4999C18.8516 10.501 18.2213 10.7116 17.7028 11.1001C17.1843 11.4887 16.8053 12.0345 16.6223 12.6561L12.6651 12.0936C12.4847 12.0681 12.3198 11.9778 12.2011 11.8396L8.85234 7.92643C9.47887 7.60888 9.97412 7.08155 10.2518 6.43635C10.5294 5.79114 10.5719 5.06896 10.3717 4.39567C10.1716 3.72237 9.74153 3.14065 9.15651 2.75189C8.57149 2.36312 7.86861 2.19196 7.17035 2.26823C6.47209 2.3445 5.82273 2.66337 5.33543 3.16926C4.84814 3.67515 4.55381 4.33599 4.50373 5.03662C4.45365 5.73725 4.65101 6.43323 5.0614 7.00328C5.4718 7.57334 6.06921 7.98131 6.74952 8.15611V15.8436C6.04253 16.0262 5.42638 16.4603 5.01657 17.0646C4.60676 17.669 4.43143 18.402 4.52343 19.1264C4.61544 19.8507 4.96847 20.5167 5.51635 20.9994C6.06423 21.482 6.76934 21.7484 7.49952 21.7484C8.2297 21.7484 8.93482 21.482 9.4827 20.9994C10.0306 20.5167 10.3836 19.8507 10.4756 19.1264C10.5676 18.402 10.3923 17.669 9.98247 17.0646C9.57267 16.4603 8.95652 16.0262 8.24952 15.8436V9.52768L11.062 12.8089C11.4175 13.2236 11.9116 13.4949 12.4523 13.5721L16.5773 14.1608C16.7018 14.7121 16.9796 15.217 17.3785 15.6173C17.7774 16.0177 18.2813 16.2972 18.8321 16.4237C19.3829 16.5502 19.9583 16.5186 20.4919 16.3324C21.0255 16.1462 21.4957 15.8131 21.8483 15.3714C22.2009 14.9297 22.4215 14.3974 22.4848 13.8357C22.548 13.2741 22.4514 12.7061 22.2059 12.197C21.9605 11.6879 21.5762 11.2585 21.0974 10.9582C20.6186 10.658 20.0647 10.4991 19.4995 10.4999ZM8.99952 18.7499C8.99952 19.0465 8.91155 19.3365 8.74673 19.5832C8.58191 19.8299 8.34764 20.0222 8.07355 20.1357C7.79946 20.2492 7.49786 20.2789 7.20689 20.221C6.91592 20.1632 6.64864 20.0203 6.43886 19.8105C6.22909 19.6007 6.08622 19.3335 6.02835 19.0425C5.97047 18.7515 6.00017 18.4499 6.1137 18.1758C6.22724 17.9017 6.41949 17.6675 6.66617 17.5027C6.91284 17.3378 7.20285 17.2499 7.49952 17.2499C7.89735 17.2499 8.27888 17.4079 8.56018 17.6892C8.84149 17.9705 8.99952 18.352 8.99952 18.7499ZM19.4995 14.9999C19.2029 14.9999 18.9128 14.9119 18.6662 14.7471C18.4195 14.5822 18.2272 14.348 18.1137 14.0739C18.0002 13.7998 17.9705 13.4982 18.0283 13.2072C18.0862 12.9163 18.2291 12.649 18.4389 12.4392C18.6486 12.2294 18.9159 12.0866 19.2069 12.0287C19.4979 11.9708 19.7995 12.0005 20.0735 12.114C20.3476 12.2276 20.5819 12.4198 20.7467 12.6665C20.9115 12.9132 20.9995 13.2032 20.9995 13.4999C20.9995 13.8977 20.8415 14.2792 20.5602 14.5605C20.2789 14.8418 19.8973 14.9999 19.4995 14.9999Z" fill="#8F00FF" />
  </svg>
}

function MediaSvg() {
  return <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
    <path d="M21.7501 20.2499H17.1901C19.177 18.9981 20.645 17.071 21.3242 14.8231C22.0033 12.5751 21.8479 10.1575 20.8866 8.01501C19.9252 5.87251 18.2226 4.14919 16.0918 3.16208C13.961 2.17496 11.5455 1.99044 9.28951 2.64246C7.03354 3.29447 5.08887 4.73917 3.81324 6.71079C2.5376 8.68242 2.0168 11.0484 2.34663 13.3734C2.67646 15.6984 3.83475 17.8261 5.60841 19.3652C7.38208 20.9042 9.65183 21.7511 12.0001 21.7499H21.7501C21.949 21.7499 22.1398 21.6709 22.2805 21.5302C22.4211 21.3896 22.5001 21.1988 22.5001 20.9999C22.5001 20.801 22.4211 20.6102 22.2805 20.4696C22.1398 20.3289 21.949 20.2499 21.7501 20.2499ZM7.50014 13.8749C7.1293 13.8749 6.76678 13.7649 6.45844 13.5589C6.1501 13.3529 5.90978 13.0601 5.76786 12.7174C5.62595 12.3748 5.58882 11.9978 5.66116 11.6341C5.73351 11.2704 5.91209 10.9363 6.17431 10.6741C6.43653 10.4119 6.77063 10.2333 7.13434 10.1609C7.49806 10.0886 7.87506 10.1257 8.21767 10.2676C8.56028 10.4095 8.85311 10.6499 9.05914 10.9582C9.26517 11.2666 9.37514 11.6291 9.37514 11.9999C9.37514 12.4972 9.17759 12.9741 8.82596 13.3257C8.47433 13.6774 7.99742 13.8749 7.50014 13.8749ZM12.0001 18.3749C11.6293 18.3749 11.2668 18.2649 10.9584 18.0589C10.6501 17.8529 10.4098 17.5601 10.2679 17.2174C10.1259 16.8748 10.0888 16.4978 10.1612 16.1341C10.2335 15.7704 10.4121 15.4363 10.6743 15.1741C10.9365 14.9119 11.2706 14.7333 11.6343 14.6609C11.9981 14.5886 12.3751 14.6257 12.7177 14.7676C13.0603 14.9095 13.3531 15.1499 13.5591 15.4582C13.7652 15.7666 13.8751 16.1291 13.8751 16.4999C13.8751 16.9972 13.6776 17.4741 13.326 17.8257C12.9743 18.1774 12.4974 18.3749 12.0001 18.3749ZM12.0001 9.37491C11.6293 9.37491 11.2668 9.26494 10.9584 9.05891C10.6501 8.85289 10.4098 8.56005 10.2679 8.21744C10.1259 7.87483 10.0888 7.49783 10.1612 7.13411C10.2335 6.7704 10.4121 6.43631 10.6743 6.17408C10.9365 5.91186 11.2706 5.73328 11.6343 5.66094C11.9981 5.58859 12.3751 5.62572 12.7177 5.76763C13.0603 5.90955 13.3531 6.14987 13.5591 6.45821C13.7652 6.76656 13.8751 7.12907 13.8751 7.49991C13.8751 7.99719 13.6776 8.4741 13.326 8.82573C12.9743 9.17736 12.4974 9.37491 12.0001 9.37491ZM14.6251 11.9999C14.6251 11.6291 14.7351 11.2666 14.9411 10.9582C15.1472 10.6499 15.44 10.4095 15.7826 10.2676C16.1252 10.1257 16.5022 10.0886 16.8659 10.1609C17.2296 10.2333 17.5637 10.4119 17.826 10.6741C18.0882 10.9363 18.2668 11.2704 18.3391 11.6341C18.4115 11.9978 18.3743 12.3748 18.2324 12.7174C18.0905 13.0601 17.8502 13.3529 17.5418 13.5589C17.2335 13.7649 16.871 13.8749 16.5001 13.8749C16.0029 13.8749 15.5259 13.6774 15.1743 13.3257C14.8227 12.9741 14.6251 12.4972 14.6251 11.9999Z" fill="#8F00FF" />
  </svg>
}